### ISSUE TITLE
格式的统一问题

### ISSUE THREAD

**Issue by Qquanwei** [wangzhongxin/algorithm#3]
我看到你这份提交 [4359cea81685e08244ce09bace4512f6c4ab3a24](https://github.com/wangzhongxin/algorithm/commit/4359cea81685e08244ce09bace4512f6c4ab3a24)中代码格式似乎有点问题。
  
  因为本地不同编辑器的设置不同会导致代码修改时缩进之间产生差异，共同编码提交时造成没必要的提交。
例如你代码中是4个space，我的vim是2个space，我在修改你代码时不小心会把你原来的代码缩进为2spaces，这样产生的变更是没必要的。

 所以建议在本地编辑器端配置 代码缩进统一。
 我的如下：
   tab 会替换为2个space
   代码层级缩进 2spaces

**Comment by wangzhongxin** [comment]
@Qquanwei  
默认不是4个空格?

**Comment by Qquanwei** [comment]
@wangzhongxin 对vim/emacs而言，2个空格更友好点

**Comment by wangzhongxin** [comment]
@Qquanwei  我一般习惯4个空格的缩进

**Comment by wangzhongxin** [comment]
@Qquanwei  别人的库，我能不能直接clone到本地然后进行提交，不用fork到自己的仓库。

**Comment by Qquanwei** [comment]
不行

**Comment by Qquanwei** [comment]
可以找一个本地配置编辑器格式的插件来定制仓库内的统一格式
